-- DROP EXISTING DATABASE
DROP TABLE IF EXISTS ListenerUserID CASCADE;
DROP TABLE IF EXISTS ListenerEmail CASCADE;
DROP TABLE IF EXISTS ArtistUserID CASCADE;
DROP TABLE IF EXISTS ArtistEmail CASCADE;
DROP TABLE IF EXISTS ArtistName CASCADE;
DROP TABLE IF EXISTS CreatePlaylist CASCADE;
DROP TABLE IF EXISTS Album CASCADE;
DROP TABLE IF EXISTS CreateAlbum CASCADE;
DROP TABLE IF EXISTS ContainSong CASCADE;
DROP TABLE IF EXISTS PlaylistIncludesSongs CASCADE;
DROP TABLE IF EXISTS Genre CASCADE;
DROP TABLE IF EXISTS HaveSongs CASCADE;
DROP TABLE IF EXISTS Label CASCADE;
DROP TABLE IF EXISTS UnderLabel CASCADE;
DROP TABLE IF EXISTS IsParentOfLabel CASCADE;

DROP DATABASE IF EXISTS streamline_db;

--DROP OWNED BY sl_admin;
--DROP USER IF EXISTS sl_admin;



-- CREATE USER TO BE USED IN DJANGO
CREATE USER sl_admin WITH password '12345';
--ALTER ROLE sl_admin CREATEDB;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO sl_admin;
-- CREATE DATABASE
CREATE DATABASE streamline_db;
