# Generated by Django 2.0.7 on 2018-07-24 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listeneremail',
            name='email',
            field=models.ForeignKey(db_column='email', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main.Listeneruserid', to_field='email'),
        ),
    ]
